version: '3'

services:
  dump_server:
    build:
      context: ./cron-server
    container_name: ${SERVER_NAME}
    restart: unless-stopped
#    volumes:
#      - ./cron-server/crons/scripts:/home/db-backups/scripts
#      - ./cron-server/crons/dumps:/home/db-backups/dumps